### PR TITLE
Added Error Messages for Alexa Internet and Fact Checks

### LINKED ISSUE #708: Timeout for Alexa Internet
### Problem

- When ```Alexa Internet```  is clicked for Website Rankings with slow internet, it keeps on loading the page until the page is closed. 
- It also shows the loading status if the internet is completely disconnected. 

alexa

### Solution

We could add a timeout feature so that it  could display some message if response is not fetched within a timespan.

### PR DESCRIPTION
**Pull request by the-pro**
Resloves #703 

Added error messages to fact checks for network errors.

Resolves #708 
Added Error messages for Alexa Internet for network errors.

Alexa_solve

### CODE REVIEW

**Comment by the-pro** [comment]
@cgorringe @anishsarangi Could you please review this. Thanks

**Comment by anishsarangi** [comment]
Hello @the-pro . I would like to add few points:
1. It’s good practice to create a new branch when working with forked repositories. Please have a look at it https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/
2. I also saw few commits with same commit message. Please see this how to write a proper git commit message https://chris.beams.io/posts/git-commit/

**Comment by the-pro** [comment]
Hi @anishsarangi . Thanks for sharing those articles. I went through both of them. Can i submit another PR implementing those changes?

**Comment by cgorringe** [comment]
@the-pro Looks good! I'll merge it in.

**Pull request merged**
