### PR TITLE
Fix Search box multi-saves and remove api calls

### LINKED ISSUE #901: Save Page Now is opening 6 tabs instead of 1 when logged out
**Describe the bug**
If a user is not logged in and when it try to save a url through the input box in the extension ui, it is opening 6 tabs simultaneously.
**To Reproduce**
1. Go to any URL
2. Click on the extension and make sure that you are logged out
3. Type any url in the extension and click "Save Page Now"
4. You will see 6 tabs opening simultaneously

**Expected behavior**
It should open 1 tab

### PR DESCRIPTION
**Pull request by cgorringe**
fixes #901 and #909
replaces PR #903

### CODE REVIEW

**Comment by infojunkie** [comment]
Looks good to me. Since you're working on this page, I suggest to also make sure that clicking anywhere outside the dropdown closes it. Including and especially clicking in the search text box.

**Review by infojunkie — CHANGES_REQUESTED** [review]
Looks good to me. Since you're working on this page, I suggest to also make sure that clicking anywhere outside the dropdown closes it. Including and especially clicking in the search text box.

**Comment by cgorringe** [comment]
now also fixes #910

**Review by infojunkie — APPROVED** [review]
Thanks, works well now.

**Pull request merged**
