### PR TITLE
Maintaining CodeBase Consistency #338

### PR DESCRIPTION
**Pull request by Chaitanya31612**
Used the following convention:

- Using camelCase for functions/methods
- Using lowecase_underscore for a variable name
- Using UPPERCASE for Constants

Made changes in files:
        modified:   test/annotation.spec.js
        modified:   webextension/scripts/alexa.js
        modified:   webextension/scripts/annotation.js
        modified:   webextension/scripts/context.js
        modified:   webextension/scripts/domaintools.js
        modified:   webextension/scripts/overview.js
        modified:   webextension/scripts/popup.js
        modified:   webextension/scripts/resource_list.js
        modified:   webextension/scripts/tagcloud.js

### CODE REVIEW

**Comment by cgorringe** [comment]
@Chaitanya31612 Unfortunately in Javascript `const` doesn't really mean constant, but _one-time assignment._ So I actually prefer that most (if not all) of the renaming to UPPERCASE be reverted back to lowercase or camelCase, and use UPPERCASE only for true constants like `const PI = 3.14159`. I should probably add this to the Style Guide!

**Comment by Chaitanya31612** [comment]
Okay @cgorringe, I'll make that change. Thanks for the feedback.

**Comment by Chaitanya31612** [comment]
@cgorringe, I've committed the changes which you suggested. Please review it.

**Comment by Chaitanya31612** [comment]
@cgorringe please guide me for further changes and have a look at the updated changes.
Thanks.

**Comment by cgorringe** [comment]
Thanks for your help! I just need to merge some other code in so will apply this PR after that, so that's why it's been delayed.

**Comment by Chaitanya31612** [comment]
> Thanks for your help! I just need to merge some other code in so will apply this PR after that, so that's why it's been delayed.

Glad to help! Would be happy to do contribute more.

**Comment by Chaitanya31612** [comment]
@cgorringe please review my pull request and suggest changes if any

**Comment by Chaitanya31612** [comment]
@cgorringe I'd like to know whether I can join the community, I mean to join any channels on slack, gitter, or something for the internet archive?

**Comment by cgorringe** [comment]
Looks good!

**Pull request merged**
