### PR TITLE
Continuous integration Github action

### LINKED ISSUE #697: Adding continuous Integration
**Is your feature request related to a problem/ issue? Please describe.**
Add a Github action for continuous integration. The extension has a fairly elaborate set of tests I believe adding a CI action will help make the process of PR review easy for the maintainers.

**Describe the solution you'd like**
Adding a Github action

**Describe alternatives you've considered**
Travis CI or Circle CI

**Additional context**
N/A

I can take this up if you approve it.

### PR DESCRIPTION
**Pull request by sarthakkundra**
Created a new directory inside `.github` and added the continuous integration action.

Closes #697

### CODE REVIEW

**Comment by cgorringe** [comment]
I still need to test this. Is the `yarn.lock` file necessary? The CI script looks like it's just using `npm` so it doesn't look like it's using Yarn? I'm not that familiar with it, but would prefer we don't use 2 lock files for 2 separate package managers if we can stick with one.

**Comment by sarthakkundra** [comment]
Hey @cgorringe . You're right, it is not necessary. I personally use `Yarn` as my package manager, that is why it must've gotten added there. Let me remove that for you right now.

**Comment by sarthakkundra** [comment]
There you go @cgorringe . Let me know if any other changes are required.

**Comment by cgorringe** [comment]
If I'm reading this correctly, it looks like it would update the npm modules and create the build.js file on every pull request. I think I'd rather that be done manually. Let's start with just `npm test` for now.

**Comment by sarthakkundra** [comment]
@cgorringe It will not update the npm modules, but rather install them. Also, yes, you are correct. It will create the `build.js` file. So I'm removing the `npm run build` command. Let me know if any other changes are required.

**Comment by cgorringe** [comment]
OK, we'll merge this and see how it goes!

**Pull request merged**
