### PR TITLE
Added Outlink and Screenshot option to Bulksave

### PR DESCRIPTION
**Pull request by Yashraj1406**
This is issue number #691. Added Outlink and Screenshot option to Bulksave

### CODE REVIEW

**Comment by Yashraj1406** [comment]
@cgorringe, Please review this

**Comment by cgorringe** [comment]
Testing. Getting rate limiting bugs. I'll try to fix.

**Comment by Yashraj1406** [comment]
Thank you @cgorringe, but is there anything from my side which I can fix as I will be more than happy to learn and contribute

**Comment by cgorringe** [comment]
Thanks @Yashraj1406, after trying it out, I think saving Outlinks isn't going to work right now because while the server is processing the outlinks, it hits the save limit when trying to save more URLs. Maybe we can process the outlinks one by one in the extension, but for now I think we should leave it out.

Saving the screenshot works, so I kept that in.

**Pull request merged**
