### PR TITLE
Enhancement/popup btn tab fix

### PR DESCRIPTION
**Pull request by VishnuRaghavan**
Added tab navigation for popup buttons.
Replaced stock blue outlines of buttons with its own background selected colour while on focus.

### CODE REVIEW

**Comment by cgorringe** [comment]
Thanks for these great improvements!

Some items to improve further:
- Let's see if we can keep the UI the same for the Save Page Now button with options underneath without adding space in between.
- In Dark mode, simple tweak needed for SPN button background color which shows up as white corners.
- Pressing Space or Enter on Outlinks, Screenshot, Social share buttons, and bottom toolbar buttons should activate their function.
- First item focused could be the Search field instead of the top logo.

**Comment by VishnuRaghavan** [comment]
Is it okay to make above mentioned changes on to same branch ?

**Comment by VishnuRaghavan** [comment]
> * In Dark mode, simple tweak needed for SPN button background color which shows up as white corners.

Which browser have you used to test, im using mac os i can't see white corners around SPN.  Im attaching a screen shot please check.

Screenshot 2022-05-07 at 1 18 01 AM

**Comment by cgorringe** [comment]
It's fine to use the same branch!

I'm getting the white corners only when "URL not supported" and when the button flips. I'm using Chrome on macOS.

white-corners

**Comment by VishnuRaghavan** [comment]
@cgorringe okay let me check

**Comment by VishnuRaghavan** [comment]
> * Pressing Space or Enter on Outlinks, Screenshot, Social share buttons, and bottom toolbar buttons should activate their function.

For this particular fix, we might need to listen to keyup and keydown events along with key-codes. which will definitely  fix it for all browsers. I see chrome had an issue with keys not detecting during tab navigation. also sometimes its doesnt work for span elements and divs. So im gonna listen to event and take action from there.

**Comment by VishnuRaghavan** [comment]
I might need to change all popup buttons to actual button tag instead of other elements like span and div. button tag will properly work with tab navigation. This is one approach, if this cant be achieved then i would go with listening to key codes on key down events as i mentioned above.
But cleanest approach it to use button tag, let me try that first.

**Comment by VishnuRaghavan** [comment]
@cgorringe  Changes mentioned above has been added, please do check.

**Comment by cgorringe** [comment]
@VishnuRaghavan I love how it's now working using the keyboard. Nice!

So far I found these issues:
- Activating "Save Page Now" button ("Archiving...") no longer animates, which was a pretty cool effect we'd want to keep!
- While logged in, try clicking on "Outlinks" or "Screenshot" labels with the mouse - it will no longer check or uncheck the box.
- Also these labels get stuck highlighted after a mouse click.

Thanks for your work so far. I know it takes a while to get everything working just right.

**Comment by VishnuRaghavan** [comment]
Will check that.

**Comment by VishnuRaghavan** [comment]
> @VishnuRaghavan I love how it's now working using the keyboard. Nice!
> 
> So far I found these issues:
> 
> * Activating "Save Page Now" button ("Archiving...") no longer animates, which was a pretty cool effect we'd want to keep!
> * While logged in, try clicking on "Outlinks" or "Screenshot" labels with the mouse - it will no longer check or uncheck the box.
> * Also these labels get stuck highlighted after a mouse click.
> 
> Thanks for your work so far. I know it takes a while to get everything working just right.


@cgorringe  I have fixed above mentioned issues please do check.

**Comment by cgorringe** [comment]
Sorry for the delay. I tested and made some changes, reverting the last commit as the additional code made it too complex and wasn't really needed. 

I didn't succeed in getting the background to highlight while using the keyboard just using CSS, but that really wasn't needed and it's more important for the mouse UI to actually look correct while using the keyboard just needs to be functional.

**Comment by cgorringe** [comment]
The jQuery `.click()` actually isn't deprecated according to the official docs, although I did find mention of it on the net. Not sure what happened. Maybe they deprecated it at one point then changed their minds? So I'll revert those lines back next...
https://api.jquery.com/click/

**Comment by cgorringe** [comment]
This PR fixes #912 and #913
Except Safari extensions don't seem to work using the keyboard, but not much we can do about that.

**Pull request merged**
